source "https://rubygems.org"

gem "slim"
gem "padrino"
gem "mongoid"

group :development do
  gem "rake"
  gem "bundler"
  gem "pry"
  gem "byebug"
end

group :test do
  gem "rspec"
  gem "rack-test"
end

